# Generated by Django 4.1.1 on 2022-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('welcome_message', models.TextField(default='Welcome: <django.db.models.query_utils.DeferredAttribute object at 0x7f6e21e6e050> !!!')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
