# Generated by Django 4.1.1 on 2022-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='welcome_message',
            field=models.TextField(default='Welcome: <django.db.models.query_utils.DeferredAttribute object at 0x7f4dccb151e0> !!!'),
        ),
    ]
