# Generated by Django 4.1.1 on 2022-10-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_bot_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='welcome_message',
            field=models.TextField(default='Welcome: <django.db.models.query_utils.DeferredAttribute object at 0x7f497c38a710> !!!'),
        ),
    ]
